listening-port=3478
tls-listening-port=443
cert=/etc/turn-cert.pem
pkey=/etc/turn-key.pem
use-auth-secret
realm=cloudemu
min-port=40000
max-port=49000
verbose
fingerprint
lt-cred-mech
no-multicast-peers
