// CloudEmu Worker Agent gRPC 服务定义
// WorkerAgent 运行在每个 Worker 节点上，供 Control Plane 远程调用
// 负责：创建 LiveKit 房间 + 生成 Token + 管理 EmuRunner 子进程生命周期

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/worker.proto

package workerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerAgent_StartGame_FullMethodName           = "/cloudemu.worker.WorkerAgent/StartGame"
	WorkerAgent_StopGame_FullMethodName            = "/cloudemu.worker.WorkerAgent/StopGame"
	WorkerAgent_SessionStatus_FullMethodName       = "/cloudemu.worker.WorkerAgent/SessionStatus"
	WorkerAgent_GeneratePlayerToken_FullMethodName = "/cloudemu.worker.WorkerAgent/GeneratePlayerToken"
	WorkerAgent_UpdatePortMapping_FullMethodName   = "/cloudemu.worker.WorkerAgent/UpdatePortMapping"
	WorkerAgent_PauseGame_FullMethodName           = "/cloudemu.worker.WorkerAgent/PauseGame"
	WorkerAgent_ResumeGame_FullMethodName          = "/cloudemu.worker.WorkerAgent/ResumeGame"
	WorkerAgent_SaveState_FullMethodName           = "/cloudemu.worker.WorkerAgent/SaveState"
	WorkerAgent_LoadState_FullMethodName           = "/cloudemu.worker.WorkerAgent/LoadState"
	WorkerAgent_SwitchRom_FullMethodName           = "/cloudemu.worker.WorkerAgent/SwitchRom"
)

// WorkerAgentClient is the client API for WorkerAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkerAgent Worker 节点 gRPC 服务
// Control Plane 作为客户端调用此服务来管理游戏会话
type WorkerAgentClient interface {
	// StartGame 启动游戏会话
	// Worker 收到请求后：创建 LiveKit 房间 → 生成 access token → 启动 EmuRunner 子进程
	StartGame(ctx context.Context, in *StartGameRequest, opts ...grpc.CallOption) (*StartGameResponse, error)
	// StopGame 停止游戏会话
	// Worker 收到请求后：SIGTERM → 5s 超时 → SIGKILL EmuRunner 子进程 → 清理 LiveKit 房间
	StopGame(ctx context.Context, in *StopGameRequest, opts ...grpc.CallOption) (*StopGameResponse, error)
	// SessionStatus 查询游戏会话运行状态
	SessionStatus(ctx context.Context, in *SessionStatusRequest, opts ...grpc.CallOption) (*SessionStatusResponse, error)
	// GeneratePlayerToken 为指定玩家生成独立的 LiveKit token（identity="player:{user_id}"）
	// 玩家通过此 token 加入 LiveKit 房间，与 EmuRunner 的 identity 不冲突
	GeneratePlayerToken(ctx context.Context, in *GeneratePlayerTokenRequest, opts ...grpc.CallOption) (*GeneratePlayerTokenResponse, error)
	// UpdatePortMapping 更新房间的 port → player_identity 映射
	// 房主调用 AssignPort 后由 Control Plane 触发，Worker 通过 LiveKit SendData 广播到房间
	// EmuRunner 收到 control topic 包后更新 InputManager 的端口绑定
	UpdatePortMapping(ctx context.Context, in *UpdatePortMappingRequest, opts ...grpc.CallOption) (*UpdatePortMappingResponse, error)
	// PauseGame 暂停游戏模拟器运行
	// 房主调用，Worker 通过 LiveKit DataChannel (topic="control", type=0x05) 发送暂停指令到 EmuRunner
	PauseGame(ctx context.Context, in *PauseGameRequest, opts ...grpc.CallOption) (*PauseGameResponse, error)
	// ResumeGame 继续游戏模拟器运行
	// 房主调用，Worker 通过 LiveKit DataChannel (topic="control", type=0x06) 发送继续指令到 EmuRunner
	ResumeGame(ctx context.Context, in *ResumeGameRequest, opts ...grpc.CallOption) (*ResumeGameResponse, error)
	// SaveState 保存游戏存档
	// 房主调用：Worker 通过 control DataChannel (type=0x07) 令 EmuRunner 序列化到共享目录，
	// 轮询到完成标志后读取状态二进制，用预签名 URL 上传到 MinIO
	SaveState(ctx context.Context, in *SaveStateRequest, opts ...grpc.CallOption) (*SaveStateResponse, error)
	// LoadState 读取游戏存档
	// 房主调用：Worker 用预签名 URL 下载状态二进制到共享目录，通过 control DataChannel (type=0x08)
	// 令 EmuRunner 反序列化恢复游戏进度
	LoadState(ctx context.Context, in *LoadStateRequest, opts ...grpc.CallOption) (*LoadStateResponse, error)
	// SwitchRom 热切换 ROM 文件（游戏运行中切换）
	// 房主调用：Worker 下载新 ROM → 通过 stdin pipe 发送 load_rom 命令 → EmuRunner 卸载旧 ROM 并加载新 ROM
	SwitchRom(ctx context.Context, in *SwitchRomRequest, opts ...grpc.CallOption) (*SwitchRomResponse, error)
}

type workerAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerAgentClient(cc grpc.ClientConnInterface) WorkerAgentClient {
	return &workerAgentClient{cc}
}

func (c *workerAgentClient) StartGame(ctx context.Context, in *StartGameRequest, opts ...grpc.CallOption) (*StartGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartGameResponse)
	err := c.cc.Invoke(ctx, WorkerAgent_StartGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerAgentClient) StopGame(ctx context.Context, in *StopGameRequest, opts ...grpc.CallOption) (*StopGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopGameResponse)
	err := c.cc.Invoke(ctx, WorkerAgent_StopGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerAgentClient) SessionStatus(ctx context.Context, in *SessionStatusRequest, opts ...grpc.CallOption) (*SessionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionStatusResponse)
	err := c.cc.Invoke(ctx, WorkerAgent_SessionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerAgentClient) GeneratePlayerToken(ctx context.Context, in *GeneratePlayerTokenRequest, opts ...grpc.CallOption) (*GeneratePlayerTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneratePlayerTokenResponse)
	err := c.cc.Invoke(ctx, WorkerAgent_GeneratePlayerToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerAgentClient) UpdatePortMapping(ctx context.Context, in *UpdatePortMappingRequest, opts ...grpc.CallOption) (*UpdatePortMappingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePortMappingResponse)
	err := c.cc.Invoke(ctx, WorkerAgent_UpdatePortMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerAgentClient) PauseGame(ctx context.Context, in *PauseGameRequest, opts ...grpc.CallOption) (*PauseGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseGameResponse)
	err := c.cc.Invoke(ctx, WorkerAgent_PauseGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerAgentClient) ResumeGame(ctx context.Context, in *ResumeGameRequest, opts ...grpc.CallOption) (*ResumeGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeGameResponse)
	err := c.cc.Invoke(ctx, WorkerAgent_ResumeGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerAgentClient) SaveState(ctx context.Context, in *SaveStateRequest, opts ...grpc.CallOption) (*SaveStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveStateResponse)
	err := c.cc.Invoke(ctx, WorkerAgent_SaveState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerAgentClient) LoadState(ctx context.Context, in *LoadStateRequest, opts ...grpc.CallOption) (*LoadStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadStateResponse)
	err := c.cc.Invoke(ctx, WorkerAgent_LoadState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerAgentClient) SwitchRom(ctx context.Context, in *SwitchRomRequest, opts ...grpc.CallOption) (*SwitchRomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwitchRomResponse)
	err := c.cc.Invoke(ctx, WorkerAgent_SwitchRom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerAgentServer is the server API for WorkerAgent service.
// All implementations must embed UnimplementedWorkerAgentServer
// for forward compatibility.
//
// WorkerAgent Worker 节点 gRPC 服务
// Control Plane 作为客户端调用此服务来管理游戏会话
type WorkerAgentServer interface {
	// StartGame 启动游戏会话
	// Worker 收到请求后：创建 LiveKit 房间 → 生成 access token → 启动 EmuRunner 子进程
	StartGame(context.Context, *StartGameRequest) (*StartGameResponse, error)
	// StopGame 停止游戏会话
	// Worker 收到请求后：SIGTERM → 5s 超时 → SIGKILL EmuRunner 子进程 → 清理 LiveKit 房间
	StopGame(context.Context, *StopGameRequest) (*StopGameResponse, error)
	// SessionStatus 查询游戏会话运行状态
	SessionStatus(context.Context, *SessionStatusRequest) (*SessionStatusResponse, error)
	// GeneratePlayerToken 为指定玩家生成独立的 LiveKit token（identity="player:{user_id}"）
	// 玩家通过此 token 加入 LiveKit 房间，与 EmuRunner 的 identity 不冲突
	GeneratePlayerToken(context.Context, *GeneratePlayerTokenRequest) (*GeneratePlayerTokenResponse, error)
	// UpdatePortMapping 更新房间的 port → player_identity 映射
	// 房主调用 AssignPort 后由 Control Plane 触发，Worker 通过 LiveKit SendData 广播到房间
	// EmuRunner 收到 control topic 包后更新 InputManager 的端口绑定
	UpdatePortMapping(context.Context, *UpdatePortMappingRequest) (*UpdatePortMappingResponse, error)
	// PauseGame 暂停游戏模拟器运行
	// 房主调用，Worker 通过 LiveKit DataChannel (topic="control", type=0x05) 发送暂停指令到 EmuRunner
	PauseGame(context.Context, *PauseGameRequest) (*PauseGameResponse, error)
	// ResumeGame 继续游戏模拟器运行
	// 房主调用，Worker 通过 LiveKit DataChannel (topic="control", type=0x06) 发送继续指令到 EmuRunner
	ResumeGame(context.Context, *ResumeGameRequest) (*ResumeGameResponse, error)
	// SaveState 保存游戏存档
	// 房主调用：Worker 通过 control DataChannel (type=0x07) 令 EmuRunner 序列化到共享目录，
	// 轮询到完成标志后读取状态二进制，用预签名 URL 上传到 MinIO
	SaveState(context.Context, *SaveStateRequest) (*SaveStateResponse, error)
	// LoadState 读取游戏存档
	// 房主调用：Worker 用预签名 URL 下载状态二进制到共享目录，通过 control DataChannel (type=0x08)
	// 令 EmuRunner 反序列化恢复游戏进度
	LoadState(context.Context, *LoadStateRequest) (*LoadStateResponse, error)
	// SwitchRom 热切换 ROM 文件（游戏运行中切换）
	// 房主调用：Worker 下载新 ROM → 通过 stdin pipe 发送 load_rom 命令 → EmuRunner 卸载旧 ROM 并加载新 ROM
	SwitchRom(context.Context, *SwitchRomRequest) (*SwitchRomResponse, error)
	mustEmbedUnimplementedWorkerAgentServer()
}

// UnimplementedWorkerAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerAgentServer struct{}

func (UnimplementedWorkerAgentServer) StartGame(context.Context, *StartGameRequest) (*StartGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartGame not implemented")
}
func (UnimplementedWorkerAgentServer) StopGame(context.Context, *StopGameRequest) (*StopGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopGame not implemented")
}
func (UnimplementedWorkerAgentServer) SessionStatus(context.Context, *SessionStatusRequest) (*SessionStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SessionStatus not implemented")
}
func (UnimplementedWorkerAgentServer) GeneratePlayerToken(context.Context, *GeneratePlayerTokenRequest) (*GeneratePlayerTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GeneratePlayerToken not implemented")
}
func (UnimplementedWorkerAgentServer) UpdatePortMapping(context.Context, *UpdatePortMappingRequest) (*UpdatePortMappingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePortMapping not implemented")
}
func (UnimplementedWorkerAgentServer) PauseGame(context.Context, *PauseGameRequest) (*PauseGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseGame not implemented")
}
func (UnimplementedWorkerAgentServer) ResumeGame(context.Context, *ResumeGameRequest) (*ResumeGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeGame not implemented")
}
func (UnimplementedWorkerAgentServer) SaveState(context.Context, *SaveStateRequest) (*SaveStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveState not implemented")
}
func (UnimplementedWorkerAgentServer) LoadState(context.Context, *LoadStateRequest) (*LoadStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadState not implemented")
}
func (UnimplementedWorkerAgentServer) SwitchRom(context.Context, *SwitchRomRequest) (*SwitchRomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SwitchRom not implemented")
}
func (UnimplementedWorkerAgentServer) mustEmbedUnimplementedWorkerAgentServer() {}
func (UnimplementedWorkerAgentServer) testEmbeddedByValue()                     {}

// UnsafeWorkerAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerAgentServer will
// result in compilation errors.
type UnsafeWorkerAgentServer interface {
	mustEmbedUnimplementedWorkerAgentServer()
}

func RegisterWorkerAgentServer(s grpc.ServiceRegistrar, srv WorkerAgentServer) {
	// If the following call panics, it indicates UnimplementedWorkerAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerAgent_ServiceDesc, srv)
}

func _WorkerAgent_StartGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerAgentServer).StartGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerAgent_StartGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerAgentServer).StartGame(ctx, req.(*StartGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerAgent_StopGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerAgentServer).StopGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerAgent_StopGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerAgentServer).StopGame(ctx, req.(*StopGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerAgent_SessionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerAgentServer).SessionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerAgent_SessionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerAgentServer).SessionStatus(ctx, req.(*SessionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerAgent_GeneratePlayerToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneratePlayerTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerAgentServer).GeneratePlayerToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerAgent_GeneratePlayerToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerAgentServer).GeneratePlayerToken(ctx, req.(*GeneratePlayerTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerAgent_UpdatePortMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePortMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerAgentServer).UpdatePortMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerAgent_UpdatePortMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerAgentServer).UpdatePortMapping(ctx, req.(*UpdatePortMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerAgent_PauseGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerAgentServer).PauseGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerAgent_PauseGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerAgentServer).PauseGame(ctx, req.(*PauseGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerAgent_ResumeGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerAgentServer).ResumeGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerAgent_ResumeGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerAgentServer).ResumeGame(ctx, req.(*ResumeGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerAgent_SaveState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerAgentServer).SaveState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerAgent_SaveState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerAgentServer).SaveState(ctx, req.(*SaveStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerAgent_LoadState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerAgentServer).LoadState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerAgent_LoadState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerAgentServer).LoadState(ctx, req.(*LoadStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerAgent_SwitchRom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwitchRomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerAgentServer).SwitchRom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerAgent_SwitchRom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerAgentServer).SwitchRom(ctx, req.(*SwitchRomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerAgent_ServiceDesc is the grpc.ServiceDesc for WorkerAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloudemu.worker.WorkerAgent",
	HandlerType: (*WorkerAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartGame",
			Handler:    _WorkerAgent_StartGame_Handler,
		},
		{
			MethodName: "StopGame",
			Handler:    _WorkerAgent_StopGame_Handler,
		},
		{
			MethodName: "SessionStatus",
			Handler:    _WorkerAgent_SessionStatus_Handler,
		},
		{
			MethodName: "GeneratePlayerToken",
			Handler:    _WorkerAgent_GeneratePlayerToken_Handler,
		},
		{
			MethodName: "UpdatePortMapping",
			Handler:    _WorkerAgent_UpdatePortMapping_Handler,
		},
		{
			MethodName: "PauseGame",
			Handler:    _WorkerAgent_PauseGame_Handler,
		},
		{
			MethodName: "ResumeGame",
			Handler:    _WorkerAgent_ResumeGame_Handler,
		},
		{
			MethodName: "SaveState",
			Handler:    _WorkerAgent_SaveState_Handler,
		},
		{
			MethodName: "LoadState",
			Handler:    _WorkerAgent_LoadState_Handler,
		},
		{
			MethodName: "SwitchRom",
			Handler:    _WorkerAgent_SwitchRom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/worker.proto",
}
