// CloudEmu Worker Agent gRPC 服务定义
// WorkerAgent 运行在每个 Worker 节点上，供 Control Plane 远程调用
// 负责：创建 LiveKit 房间 + 生成 Token + 管理 EmuRunner 子进程生命周期

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/worker.proto

package workerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StartGameRequest 启动游戏会话请求
type StartGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                   // 房间 ID（UUIDv7 字符串），同时也是 LiveKit 房间名
	RomPath       string                 `protobuf:"bytes,2,opt,name=rom_path,json=romPath,proto3" json:"rom_path,omitempty"`                // MinIO 中的 ROM 文件路径（仅供日志/调试）
	EmulatorType  string                 `protobuf:"bytes,3,opt,name=emulator_type,json=emulatorType,proto3" json:"emulator_type,omitempty"` // 模拟器类型："nes" / "gb" / "dos"
	MaxPorts      int32                  `protobuf:"varint,4,opt,name=max_ports,json=maxPorts,proto3" json:"max_ports,omitempty"`            // 最大手柄端口数（最多4人），决定 DataChannel 数量
	RomUrl        string                 `protobuf:"bytes,5,opt,name=rom_url,json=romUrl,proto3" json:"rom_url,omitempty"`                   // MinIO 预签名下载 URL，Worker 用于下载 ROM 文件到本地临时目录
	HostUserId    string                 `protobuf:"bytes,6,opt,name=host_user_id,json=hostUserId,proto3" json:"host_user_id,omitempty"`     // 房主用户 ID，Worker 据此生成房主的独立 player token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameRequest) Reset() {
	*x = StartGameRequest{}
	mi := &file_proto_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameRequest) ProtoMessage() {}

func (x *StartGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameRequest.ProtoReflect.Descriptor instead.
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{0}
}

func (x *StartGameRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *StartGameRequest) GetRomPath() string {
	if x != nil {
		return x.RomPath
	}
	return ""
}

func (x *StartGameRequest) GetEmulatorType() string {
	if x != nil {
		return x.EmulatorType
	}
	return ""
}

func (x *StartGameRequest) GetMaxPorts() int32 {
	if x != nil {
		return x.MaxPorts
	}
	return 0
}

func (x *StartGameRequest) GetRomUrl() string {
	if x != nil {
		return x.RomUrl
	}
	return ""
}

func (x *StartGameRequest) GetHostUserId() string {
	if x != nil {
		return x.HostUserId
	}
	return ""
}

// StartGameResponse 启动游戏会话响应
type StartGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LivekitToken  string                 `protobuf:"bytes,1,opt,name=livekit_token,json=livekitToken,proto3" json:"livekit_token,omitempty"` // EmuRunner token（identity="emurunner", canPublish=true）
	LivekitRoom   string                 `protobuf:"bytes,2,opt,name=livekit_room,json=livekitRoom,proto3" json:"livekit_room,omitempty"`    // LiveKit 房间名（= room_id）
	LivekitUrl    string                 `protobuf:"bytes,3,opt,name=livekit_url,json=livekitUrl,proto3" json:"livekit_url,omitempty"`       // LiveKit 服务端 WebSocket 地址，前端/EmuRunner 用此地址连接
	HostToken     string                 `protobuf:"bytes,4,opt,name=host_token,json=hostToken,proto3" json:"host_token,omitempty"`          // 房主玩家 token（identity="player:{host_id}", canPublish=false）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameResponse) Reset() {
	*x = StartGameResponse{}
	mi := &file_proto_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameResponse) ProtoMessage() {}

func (x *StartGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameResponse.ProtoReflect.Descriptor instead.
func (*StartGameResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{1}
}

func (x *StartGameResponse) GetLivekitToken() string {
	if x != nil {
		return x.LivekitToken
	}
	return ""
}

func (x *StartGameResponse) GetLivekitRoom() string {
	if x != nil {
		return x.LivekitRoom
	}
	return ""
}

func (x *StartGameResponse) GetLivekitUrl() string {
	if x != nil {
		return x.LivekitUrl
	}
	return ""
}

func (x *StartGameResponse) GetHostToken() string {
	if x != nil {
		return x.HostToken
	}
	return ""
}

// StopGameRequest 停止游戏会话请求
type StopGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // 要停止的房间 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopGameRequest) Reset() {
	*x = StopGameRequest{}
	mi := &file_proto_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopGameRequest) ProtoMessage() {}

func (x *StopGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopGameRequest.ProtoReflect.Descriptor instead.
func (*StopGameRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{2}
}

func (x *StopGameRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// StopGameResponse 停止游戏会话响应（空消息）
type StopGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopGameResponse) Reset() {
	*x = StopGameResponse{}
	mi := &file_proto_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopGameResponse) ProtoMessage() {}

func (x *StopGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopGameResponse.ProtoReflect.Descriptor instead.
func (*StopGameResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{3}
}

// SessionStatusRequest 查询会话状态请求
type SessionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // 房间 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStatusRequest) Reset() {
	*x = SessionStatusRequest{}
	mi := &file_proto_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStatusRequest) ProtoMessage() {}

func (x *SessionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStatusRequest.ProtoReflect.Descriptor instead.
func (*SessionStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{4}
}

func (x *SessionStatusRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// SessionStatusResponse 会话状态响应
type SessionStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                       // 房间 ID
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                     // 会话状态："running" | "stopped" | "crashed"
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"` // 运行时长（秒），仅在 status=running 时有意义
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStatusResponse) Reset() {
	*x = SessionStatusResponse{}
	mi := &file_proto_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStatusResponse) ProtoMessage() {}

func (x *SessionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStatusResponse.ProtoReflect.Descriptor instead.
func (*SessionStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{5}
}

func (x *SessionStatusResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SessionStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SessionStatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

// GeneratePlayerTokenRequest 为玩家生成独立 token 请求
type GeneratePlayerTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // 房间 ID
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 玩家用户 ID，用于构造 identity="player:{user_id}"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePlayerTokenRequest) Reset() {
	*x = GeneratePlayerTokenRequest{}
	mi := &file_proto_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePlayerTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePlayerTokenRequest) ProtoMessage() {}

func (x *GeneratePlayerTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePlayerTokenRequest.ProtoReflect.Descriptor instead.
func (*GeneratePlayerTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{6}
}

func (x *GeneratePlayerTokenRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GeneratePlayerTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GeneratePlayerTokenResponse 生成玩家 token 响应
type GeneratePlayerTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // 玩家专属的 LiveKit access token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePlayerTokenResponse) Reset() {
	*x = GeneratePlayerTokenResponse{}
	mi := &file_proto_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePlayerTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePlayerTokenResponse) ProtoMessage() {}

func (x *GeneratePlayerTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePlayerTokenResponse.ProtoReflect.Descriptor instead.
func (*GeneratePlayerTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{7}
}

func (x *GeneratePlayerTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// UpdatePortMappingRequest 更新 port → player_identity 映射请求
// mapping 是当前房间所有 role=1 且 port!=null 的玩家集合（全量）
// key = port 编号（0-based），value = LiveKit identity（格式 "player:{user_id}"）
type UpdatePortMappingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                                                                // 房间 ID
	Mapping       map[int32]string       `protobuf:"bytes,2,rep,name=mapping,proto3" json:"mapping,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // port → player identity 全量映射
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePortMappingRequest) Reset() {
	*x = UpdatePortMappingRequest{}
	mi := &file_proto_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePortMappingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePortMappingRequest) ProtoMessage() {}

func (x *UpdatePortMappingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePortMappingRequest.ProtoReflect.Descriptor instead.
func (*UpdatePortMappingRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePortMappingRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *UpdatePortMappingRequest) GetMapping() map[int32]string {
	if x != nil {
		return x.Mapping
	}
	return nil
}

// UpdatePortMappingResponse 更新映射响应（空消息）
type UpdatePortMappingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePortMappingResponse) Reset() {
	*x = UpdatePortMappingResponse{}
	mi := &file_proto_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePortMappingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePortMappingResponse) ProtoMessage() {}

func (x *UpdatePortMappingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePortMappingResponse.ProtoReflect.Descriptor instead.
func (*UpdatePortMappingResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{9}
}

// PauseGameRequest 暂停游戏请求
type PauseGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // 房间 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseGameRequest) Reset() {
	*x = PauseGameRequest{}
	mi := &file_proto_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseGameRequest) ProtoMessage() {}

func (x *PauseGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseGameRequest.ProtoReflect.Descriptor instead.
func (*PauseGameRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{10}
}

func (x *PauseGameRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// PauseGameResponse 暂停游戏响应（空消息）
type PauseGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseGameResponse) Reset() {
	*x = PauseGameResponse{}
	mi := &file_proto_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseGameResponse) ProtoMessage() {}

func (x *PauseGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseGameResponse.ProtoReflect.Descriptor instead.
func (*PauseGameResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{11}
}

// ResumeGameRequest 继续游戏请求
type ResumeGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // 房间 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeGameRequest) Reset() {
	*x = ResumeGameRequest{}
	mi := &file_proto_worker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeGameRequest) ProtoMessage() {}

func (x *ResumeGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeGameRequest.ProtoReflect.Descriptor instead.
func (*ResumeGameRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{12}
}

func (x *ResumeGameRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// ResumeGameResponse 继续游戏响应（空消息）
type ResumeGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeGameResponse) Reset() {
	*x = ResumeGameResponse{}
	mi := &file_proto_worker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeGameResponse) ProtoMessage() {}

func (x *ResumeGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeGameResponse.ProtoReflect.Descriptor instead.
func (*ResumeGameResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{13}
}

var File_proto_worker_proto protoreflect.FileDescriptor

const file_proto_worker_proto_rawDesc = "" +
	"\n" +
	"\x12proto/worker.proto\x12\x0fcloudemu.worker\"\xc3\x01\n" +
	"\x10StartGameRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x19\n" +
	"\brom_path\x18\x02 \x01(\tR\aromPath\x12#\n" +
	"\remulator_type\x18\x03 \x01(\tR\femulatorType\x12\x1b\n" +
	"\tmax_ports\x18\x04 \x01(\x05R\bmaxPorts\x12\x17\n" +
	"\arom_url\x18\x05 \x01(\tR\x06romUrl\x12 \n" +
	"\fhost_user_id\x18\x06 \x01(\tR\n" +
	"hostUserId\"\x9b\x01\n" +
	"\x11StartGameResponse\x12#\n" +
	"\rlivekit_token\x18\x01 \x01(\tR\flivekitToken\x12!\n" +
	"\flivekit_room\x18\x02 \x01(\tR\vlivekitRoom\x12\x1f\n" +
	"\vlivekit_url\x18\x03 \x01(\tR\n" +
	"livekitUrl\x12\x1d\n" +
	"\n" +
	"host_token\x18\x04 \x01(\tR\thostToken\"*\n" +
	"\x0fStopGameRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"\x12\n" +
	"\x10StopGameResponse\"/\n" +
	"\x14SessionStatusRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"o\n" +
	"\x15SessionStatusResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\"N\n" +
	"\x1aGeneratePlayerTokenRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"3\n" +
	"\x1bGeneratePlayerTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xc1\x01\n" +
	"\x18UpdatePortMappingRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12P\n" +
	"\amapping\x18\x02 \x03(\v26.cloudemu.worker.UpdatePortMappingRequest.MappingEntryR\amapping\x1a:\n" +
	"\fMappingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1b\n" +
	"\x19UpdatePortMappingResponse\"+\n" +
	"\x10PauseGameRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"\x13\n" +
	"\x11PauseGameResponse\",\n" +
	"\x11ResumeGameRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"\x14\n" +
	"\x12ResumeGameResponse2\x9b\x05\n" +
	"\vWorkerAgent\x12R\n" +
	"\tStartGame\x12!.cloudemu.worker.StartGameRequest\x1a\".cloudemu.worker.StartGameResponse\x12O\n" +
	"\bStopGame\x12 .cloudemu.worker.StopGameRequest\x1a!.cloudemu.worker.StopGameResponse\x12^\n" +
	"\rSessionStatus\x12%.cloudemu.worker.SessionStatusRequest\x1a&.cloudemu.worker.SessionStatusResponse\x12p\n" +
	"\x13GeneratePlayerToken\x12+.cloudemu.worker.GeneratePlayerTokenRequest\x1a,.cloudemu.worker.GeneratePlayerTokenResponse\x12j\n" +
	"\x11UpdatePortMapping\x12).cloudemu.worker.UpdatePortMappingRequest\x1a*.cloudemu.worker.UpdatePortMappingResponse\x12R\n" +
	"\tPauseGame\x12!.cloudemu.worker.PauseGameRequest\x1a\".cloudemu.worker.PauseGameResponse\x12U\n" +
	"\n" +
	"ResumeGame\x12\".cloudemu.worker.ResumeGameRequest\x1a#.cloudemu.worker.ResumeGameResponseBAZ?github.com/StellarisJAY/cloudemu/internal/proto/worker;workerpbb\x06proto3"

var (
	file_proto_worker_proto_rawDescOnce sync.Once
	file_proto_worker_proto_rawDescData []byte
)

func file_proto_worker_proto_rawDescGZIP() []byte {
	file_proto_worker_proto_rawDescOnce.Do(func() {
		file_proto_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_worker_proto_rawDesc), len(file_proto_worker_proto_rawDesc)))
	})
	return file_proto_worker_proto_rawDescData
}

var file_proto_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_worker_proto_goTypes = []any{
	(*StartGameRequest)(nil),            // 0: cloudemu.worker.StartGameRequest
	(*StartGameResponse)(nil),           // 1: cloudemu.worker.StartGameResponse
	(*StopGameRequest)(nil),             // 2: cloudemu.worker.StopGameRequest
	(*StopGameResponse)(nil),            // 3: cloudemu.worker.StopGameResponse
	(*SessionStatusRequest)(nil),        // 4: cloudemu.worker.SessionStatusRequest
	(*SessionStatusResponse)(nil),       // 5: cloudemu.worker.SessionStatusResponse
	(*GeneratePlayerTokenRequest)(nil),  // 6: cloudemu.worker.GeneratePlayerTokenRequest
	(*GeneratePlayerTokenResponse)(nil), // 7: cloudemu.worker.GeneratePlayerTokenResponse
	(*UpdatePortMappingRequest)(nil),    // 8: cloudemu.worker.UpdatePortMappingRequest
	(*UpdatePortMappingResponse)(nil),   // 9: cloudemu.worker.UpdatePortMappingResponse
	(*PauseGameRequest)(nil),            // 10: cloudemu.worker.PauseGameRequest
	(*PauseGameResponse)(nil),           // 11: cloudemu.worker.PauseGameResponse
	(*ResumeGameRequest)(nil),           // 12: cloudemu.worker.ResumeGameRequest
	(*ResumeGameResponse)(nil),          // 13: cloudemu.worker.ResumeGameResponse
	nil,                                 // 14: cloudemu.worker.UpdatePortMappingRequest.MappingEntry
}
var file_proto_worker_proto_depIdxs = []int32{
	14, // 0: cloudemu.worker.UpdatePortMappingRequest.mapping:type_name -> cloudemu.worker.UpdatePortMappingRequest.MappingEntry
	0,  // 1: cloudemu.worker.WorkerAgent.StartGame:input_type -> cloudemu.worker.StartGameRequest
	2,  // 2: cloudemu.worker.WorkerAgent.StopGame:input_type -> cloudemu.worker.StopGameRequest
	4,  // 3: cloudemu.worker.WorkerAgent.SessionStatus:input_type -> cloudemu.worker.SessionStatusRequest
	6,  // 4: cloudemu.worker.WorkerAgent.GeneratePlayerToken:input_type -> cloudemu.worker.GeneratePlayerTokenRequest
	8,  // 5: cloudemu.worker.WorkerAgent.UpdatePortMapping:input_type -> cloudemu.worker.UpdatePortMappingRequest
	10, // 6: cloudemu.worker.WorkerAgent.PauseGame:input_type -> cloudemu.worker.PauseGameRequest
	12, // 7: cloudemu.worker.WorkerAgent.ResumeGame:input_type -> cloudemu.worker.ResumeGameRequest
	1,  // 8: cloudemu.worker.WorkerAgent.StartGame:output_type -> cloudemu.worker.StartGameResponse
	3,  // 9: cloudemu.worker.WorkerAgent.StopGame:output_type -> cloudemu.worker.StopGameResponse
	5,  // 10: cloudemu.worker.WorkerAgent.SessionStatus:output_type -> cloudemu.worker.SessionStatusResponse
	7,  // 11: cloudemu.worker.WorkerAgent.GeneratePlayerToken:output_type -> cloudemu.worker.GeneratePlayerTokenResponse
	9,  // 12: cloudemu.worker.WorkerAgent.UpdatePortMapping:output_type -> cloudemu.worker.UpdatePortMappingResponse
	11, // 13: cloudemu.worker.WorkerAgent.PauseGame:output_type -> cloudemu.worker.PauseGameResponse
	13, // 14: cloudemu.worker.WorkerAgent.ResumeGame:output_type -> cloudemu.worker.ResumeGameResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_worker_proto_init() }
func file_proto_worker_proto_init() {
	if File_proto_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_worker_proto_rawDesc), len(file_proto_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_worker_proto_goTypes,
		DependencyIndexes: file_proto_worker_proto_depIdxs,
		MessageInfos:      file_proto_worker_proto_msgTypes,
	}.Build()
	File_proto_worker_proto = out.File
	file_proto_worker_proto_goTypes = nil
	file_proto_worker_proto_depIdxs = nil
}
